termoapp/urls.py
from .views import *
from django.urls import path
from django.contrib.auth.decorators import login_required

app_name = "termoapp"
urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', logout_user, name="logout"),
    path('', login_required(UserWordView.as_view(), login_url="/termo/login/"), name="termo"),
    path('extra/', login_required(UserWordExtraView.as_view(), login_url="/termo/login/"), name="extra"),
    path('ranking/', login_required(RankingView.as_view(), login_url="/termo/login/"), name="ranking"),
    path('send/', login_required(send, login_url="/termo/login/"), name="send"),
    path('buy/', login_required(buy, login_url="/termo/login/"), name="buy"),
]

termoproject/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('termoapp:termo'))),
    path('admin/', admin.site.urls),
    path('termo/', include('termoapp.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

termoapp/models.py
from django.core.validators import MinLengthValidator
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from unidecode import unidecode
from .termo import *
from .enums import *

class BaseModel(models.Model):
    id = models.AutoField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        abstract = True

class Ranking(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    ranking = models.IntegerField(null=True, blank=True)
    score = models.IntegerField(default=0)
    coins = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Ranking"
        verbose_name_plural = "Rankings"

    def set_ranking(self):
        rankings = list(Ranking.objects.exclude(user__username="admin").order_by('-score'))
        cont = 1
        for i, ranking in enumerate(rankings):
            if (i != 0 and ranking.score != rankings[i - 1].score):
                cont += 1
            ranking.ranking = cont
            ranking.save()

    def set_score(self, user_word):
        self.score += user_word.score
        self.coins += user_word.score
        self.save()
        self.set_ranking()

    def can_buy(self):
        user_word = UserWord().get_extra_game(self.user)
        has_extra_words = UserWord().has_available_extra_words(self.user)
        if user_word:
            return user_word.finished and self.coins >= 6 and has_extra_words
        return self.coins >= 6 and has_extra_words

    def buy(self):
        if self.can_buy():
            self.coins -= 6
            extra_game = UserWord().get_extra_game(self.user)
            if extra_game:
                word = Word.objects.get(pk=extra_game.word.id+2)
            else:
                word = Word.objects.filter(date__isnull=True).first()
            user_word = UserWord.objects.create(user=self.user, word=word)
            user_word.save()
            self.save()


class Word(BaseModel):
    word = models.CharField(max_length=5, validators=[MinLengthValidator(5)])
    date = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name = "Word"
        verbose_name_plural = "Words"
        constraints = [
            models.UniqueConstraint(fields=['word'], name='unique_word')
        ]
        
    def save(self, *args, **kwargs):
        is_new = self.pk is None

        self.word = unidecode(self.word).lower().strip()
        super().save(*args, **kwargs)

        if is_new:
            users = list(User.objects.all())
            for user in users:
                UserWord.objects.create(user=user, word=self)

    def get_daily_word(self):
        try:
            date = timezone.localdate()
            daily_word = Word.objects.get(
                date__day=date.day,
                date__month=date.month,
                date__year=date.year,
            )
            return daily_word
        except Word.DoesNotExist:
            return None

class UserWord(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    type = models.CharField(max_length=5, null=True, blank=True)
    score = models.IntegerField(default=0)
    finished = models.BooleanField(default=False)

    class Meta:
        verbose_name = "UserWord"
        verbose_name_plural = "UserWords"
        constraints = [
            models.UniqueConstraint(fields=['user', 'word'], name='unique_user_word'),
        ]
    
    def save(self, *args, **kwargs):
        is_new = self.pk is None
        if is_new:
            if self.word.date:
                self.type = WordType.DAILY.value
            else:
                self.type = WordType.EXTRA.value
        super().save(*args, **kwargs)

    def get_daily_game(self, user):
        try:
            return UserWord.objects.get(user=user, type=WordType.DAILY.value, word=Word().get_daily_word())
        except UserWord.DoesNotExist:
            daily_word = Word().get_daily_word()
            if daily_word:
                new_user_word = UserWord(user=user, type=WordType.DAILY.value, word=daily_word)
                new_user_word.save()
                return new_user_word
            return None
        
    def get_extra_game(self, user):
        return UserWord.objects.filter(user=user, type=WordType.EXTRA.value).order_by('id').last()
        
    def has_available_daily_word(self):
        date = timezone.localdate()
        return Word.objects.filter(
            date__day=date.day,
            date__month=date.month,
            date__year=date.year
        ).exists()

    def has_available_extra_words(self, user):
        played_words = list(UserWord.objects.filter(
            user=user, type=WordType.EXTRA.value, finished=True
        ).values_list('word', flat=True))
        extra_words = Word.objects.filter(date__isnull=True)
        non_played_words = extra_words.exclude(word__in=played_words)
        return non_played_words.exists()
            
class Attempt(BaseModel):
    user_word = models.ForeignKey(UserWord, on_delete=models.CASCADE)
    attempt = models.CharField(max_length=5, validators=[MinLengthValidator(5)], null=True, blank=True)
    
    class Meta:
        verbose_name = "Attempt"
        verbose_name_plural = "Attempts"

    def save(self, *args, **kwargs):
        if self.user_word.finished:
            raise ValidationError("UserWord finished")
        
        super().save(*args, **kwargs)
        
        word = self.user_word.word.word
        win = Termo(word).win(self.attempt)
        attempts = len(list(Attempt.objects.filter(user_word=self.user_word)))
        if attempts == 6 or win:
            self.user_word.score = 7 - attempts if win else 0
            self.user_word.finished = True
            self.user_word.save()
            ranking = Ranking.objects.get(user=self.user_word.user)
            ranking.set_score(self.user_word)


termoapp/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.views.decorators.http import require_http_methods
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from unidecode import unidecode
from .models import *
from .termo import *
from .enums import *

@require_http_methods(["POST"])
def send(request):
    request_word = ""
    for i in range(1, 6):
        request_word += (request.POST[f'letter{i}'])
    request_word = unidecode(request_word).lower().strip()
    
    user = request.user
    type = request.POST['type']
    
    if not Word.objects.filter(word=request_word).exists():
        messages.error(request, "Invalid Word")
        return redirect('termoapp:' + type)

    if type == 'termo':
        user_word = UserWord().get_daily_game(user)
    else:
        user_word = UserWord().get_extra_game(user)
        
    Attempt.objects.create(user_word=user_word, attempt=request_word)

    return redirect('termoapp:' + type)
    
@require_http_methods(["POST"])
def buy(request):
    user = request.user
    ranking = Ranking.objects.get(user=user)
    ranking.buy()
        
    return redirect('termoapp:extra')
    
def logout_user(request):
    logout(request)
    return redirect('termoapp:termo')
    
class LoginView(generic.TemplateView):
    template_name = "termoapp/login.html"

    def post(self, request):
        if 'login' in request.POST:
            return self.handle_login(request)
        elif 'register' in request.POST:
            return self.handle_register(request)

    def handle_login(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('termoapp:termo') 
        
        return render(request, self.template_name, {'login_error': 'Invalid credentials'})

    def handle_register(self, request):
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 != password2:
            return render(request, self.template_name, {'register_error': 'Passwords do not match'})

        if User.objects.filter(username=username).exists():
            return render(request, self.template_name, {'register_error': 'Username already exists'})

        user = User.objects.create_user(username=username, password=password1)
        user.save()

        login(request, user)
        return redirect('termoapp:termo')

class UserWordView(generic.ListView):
    model = UserWord
    template_name = 'termoapp/base.html'
    context_object_name = 'attempts'
    
    def get_queryset(self):
        user = self.request.user
        user_word = UserWord().get_daily_game(user)
        word = user_word.word
        attempts = list()            
        user_attempts = list(Attempt.objects.filter(user_word=user_word).order_by('created_at').values_list('attempt'))
        for attempt in user_attempts:
            feedback = Termo(word.word).feedback(attempt[0])
            attempts.append(feedback)
            
        return attempts

    def get_context_data(self, **kwargs):
        user = self.request.user
        has_daily_word = UserWord().has_available_daily_word()
        user_word = UserWord().get_daily_game(user)
        word = user_word.word

        context = super().get_context_data(**kwargs)
        
        attempts = context['attempts'] 
        not_attempts = [True] * (6 - len(attempts))
        correct_word = None
        
        if (attempts):
            attempt = ''.join([i[0] for i in attempts[-1]])
            win = Termo(word.word).win(attempt)
            if win and not_attempts:  
                not_attempts[0] = False
                
        if len(attempts) == 6 and not win:
            correct_word = word.word

        context['attempts'] = attempts
        context['notAttempts'] = not_attempts
        context['has_daily_word'] = has_daily_word
        context['type'] = 'termo'
        context['correct_word'] = correct_word
        context['has_game'] = user_word
        return context

class UserWordExtraView(generic.ListView):
    model = UserWord
    template_name = 'termoapp/shop.html'
    context_object_name = 'attempts'
    
    def get_queryset(self):
        user = self.request.user
        user_word = UserWord().get_extra_game(user)
        attempts = list()
        
        if user_word:
            word = user_word.word
            user_attempts = list(Attempt.objects.filter(user_word=user_word).order_by('created_at').values_list('attempt'))
            for attempt in user_attempts:
                feedback = Termo(word.word).feedback(attempt[0])
                attempts.append(feedback)
        
        return attempts

    def get_context_data(self, **kwargs):
        user = self.request.user
        ranking = Ranking.objects.get(user=user)
        has_extra_words = UserWord.has_available_extra_words(self, user)

        can_buy = ranking.can_buy()

        context = super().get_context_data(**kwargs)
        
        attempts = context['attempts'] 
        not_attempts = [True] * (6 - len(attempts))
        correct_word = None

        finished = False
        user_word = UserWord().get_extra_game(user)
        if (user_word != None):
            word = user_word.word
            finished = user_word.finished
        
        if (attempts):
            attempt = ''.join([i[0] for i in attempts[-1]])
            win = Termo(word.word).win(attempt)
            if win and not_attempts:  
                not_attempts[0] = False

        if len(attempts) == 6 and not win:
            correct_word = word.word

        context['attempts'] = attempts
        context['notAttempts'] = not_attempts
        context['coins'] = ranking.coins
        context['finished'] = finished
        context['can_buy'] = can_buy
        context['has_extra_words'] = has_extra_words
        context['type'] = 'extra'
        context['correct_word'] = correct_word
        context['has_game'] = user_word != None
        return context
    
class RankingView(generic.ListView):
    model = Ranking
    template_name = 'termoapp/ranking.html'
    context_object_name = 'rankings'

    def get_queryset(self):
        user = self.request.user
        user_ranking = Ranking.objects.get(user=user)
        top10 = list(Ranking.objects.exclude(ranking__isnull=True).order_by('ranking')[:10])
        
        if (user_ranking.ranking is not None and user_ranking.ranking > 10):
            top10.append(user_ranking)
    
        return top10

templates/termoapp/base.html
{% load static %}

<html>
<link rel="stylesheet" href="{% static 'termoapp/css/base.css' %}">
{% include './navbar.html' %}
    <section class="game-section">
        <div class="words-container">   
            {% for attempt in attempts %}
                {% for letter in attempt %}
                    {% if letter.1 == 1 %}
                        <input type="text" value="{{ letter.0 }}" maxlength="1" disabled="true" class="right" id="attempt{{ forloop.parentloop.counter }}">
                    {% elif letter.1 == 2 %}
                        <input type="text" value="{{ letter.0 }}" maxlength="1" disabled="true" class="wrong-place" id="attempt{{ forloopforloop.parentloop.counter }}">
                    {% else %}
                        <input type="text" value="{{ letter.0 }}" maxlength="1" disabled="true" class="wrong" id="attempt{{ forloop.parentloop.counter }}">
                    {% endif %}   
                {% endfor %}
            {% endfor %}
            {% for notAttempt in notAttempts %}
                {% if forloop.first and notAttempt and has_game %}
                    <form action="{% url 'termoapp:send' %}" method="POST" style="display: contents">
                        {% csrf_token %}
                        <input type="hidden" name="type" value="{{ type }}">
                        <input name="letter1" type="text" maxlength="1" class="letter-input" autocomplete="off">
                        <input name="letter2" type="text" maxlength="1" class="letter-input" autocomplete="off">
                        <input name="letter3" type="text" maxlength="1" class="letter-input" autocomplete="off">
                        <input name="letter4" type="text" maxlength="1" class="letter-input" autocomplete="off">
                        <input name="letter5" type="text" maxlength="1" class="letter-input" autocomplete="off">
                    </form>
                {% else %}
                    <input type="text" maxlength="1" class="unselected" disabled="true">
                    <input type="text" maxlength="1" class="unselected" disabled="true">
                    <input type="text" maxlength="1" class="unselected" disabled="true">
                    <input type="text" maxlength="1" class="unselected" disabled="true">
                    <input type="text" maxlength="1" class="unselected" disabled="true">
                {% endif %}
            {% endfor %}
        </div>
    </section>

    {% if not has_daily_word and type == "termo" %}
        <p class="no-words">Não há mais palavras disponíveis!</p>
    {% endif %}

    {% if messages %}
        {% for message in messages %}
            <p class="invalid-word">Palavra inválida!</p>
        {% endfor %}
    {% endif %}

    {% if correct_word %}
        <p class="correct-word">A palavra correta era: {{ correct_word | upper }}</p>
    {% endif %}
    
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const letterInputs = document.querySelectorAll('.letter-input');
            const storedWord = localStorage.getItem('currentWord') || '';
            const invalidWord = document.querySelector('.invalid-word');

            //preencher palavra inválida
            if (invalidWord) {
                storedWord.split('').forEach((char, index) => {
                    letterInputs[index].value = char;
                });
                letterInputs[4].focus();
            } else {
                letterInputs[0].focus();
            }
        
            letterInputs.forEach((input, index) => {
                
                // animação palavra inválida
                if (invalidWord) {
                    input.classList.add('shake');
                    setTimeout(() => {
                        input.classList.remove('shake');
                    }, 500);
                }

                const nextInput = letterInputs[index + 1];
                const prevInput = letterInputs[index - 1];

                // digitar letras
                input.addEventListener('input', (event) => {
                    const isLetter = event.data && event.data.match(/^[a-zA-Z]+$/);
                        if (!isLetter) {
                            input.value = '';
                        } 
                        else if (input.value) {
                            const nextInput = letterInputs[index + 1];

                            if (nextInput) {
                                nextInput.focus();
                            }
                        }

                        // armazenar no localstorage
                        const currentWord = Array.from(letterInputs).map(input => input.value).join('');
                        localStorage.setItem('currentWord', currentWord);
                });
        
                input.addEventListener('keydown', (event) => {
                    // envio e animação
                    if (event.keyCode === 13) {
                        event.preventDefault();
                        const allInputsFilled = Array.from(letterInputs).every(input => input.value);
            
                        if (allInputsFilled) {
                        
                            const form = letterInputs[0].closest('form');

                            const animationPromises = Array.from(letterInputs).map((input, index) => {
                                return new Promise(resolve => {
                                    setTimeout(() => {
                                        input.classList.add('flip-input');
                                        setTimeout(() => {
                                            resolve();
                                        }, 400);
                                    }, index * 300);
                                });
                            });

                            Promise.all(animationPromises).then(() => {
                                form.submit();
                            });
                        }

                    }

                    // apagar
                    else if (event.keyCode === 8) {
                        if (input.value) {
                            input.value = '';
                        } else if (prevInput) {
                            prevInput.focus();
                        }
                    }

                    // mover com setas
                    else if (event.keyCode === 39) {
                        if (nextInput) {
                            nextInput.focus();
                        }
                    } 
                
                    else if (event.keyCode === 37) {
                        if (prevInput) {
                            prevInput.focus();
                        }
                    }
                });
            });
        });
        

        // animação acerto
        const attempts = "{{ attempts | safe }}";
        const attemptsArray = eval(attempts);

        let c = 0;
        attemptsArray[attemptsArray.length - 1].forEach((tuple) => {
            if (tuple === 1) {
                c++;
            }
        });

        const lastAttemptInputs = document.querySelectorAll(`#attempt${attemptsArray.length}`)

        if (c === 5) {
            lastAttemptInputs.forEach((input, index) => {
                setTimeout(() => {
                    input.classList.add('jump');
                }, index * 100);    
            }); 
        }

    </script>
</html>

templates/termoapp/login.html
{% load static %}

<html>
<link rel="stylesheet" href="{% static 'termoapp/css/login.css' %}">

  <div class="container">
    <h1 class="login-title">LOGIN</h1>
    <form method="POST" class="login-form">
      {% csrf_token %}
      <input type="hidden" name="login" value="1">
      <input type="text" placeholder="Nome de usuário" class="input" name="username" required>
      <input type="password" placeholder="Senha" class="input" name="password" required>
      <button type="submit" class="action-button login">Entrar</button>
      {% if login_error and login_error == 'Invalid credentials' %}
        <p style="color: red;">Credenciais Inválidas</p>
      {% endif %}
    </form>
    <h1 class="register-title hidden">CADASTRAR</h1>
    <form method="POST" class="register-form hidden">
      {% csrf_token %}
      <input type="hidden" name="register" value="1">
      <input type="text" name="username" placeholder="Nome de usuário" class="input" required>
      <input type="password" name="password1" placeholder="Senha" class="input" required>
      <input type="password" name="password2" placeholder="Confirmar senha" class="input" required>
      <button class="action-button register">Cadastrar</button>
      {% if register_error and register_error == 'Passwords do not match' %}
        <p style="color: red;">Senhas não coincidem</p>
      {% endif %}
      {% if register_error and register_error == 'Username already exists' %}
        <p style="color: red;">Nome de Usuário já existe</p>
      {% endif %}

    </form>
    <span class="change-form">Fazer Cadastro</span>
  </div>

  <script>
    document.querySelector('.change-form').addEventListener('click', () => {
      const loginForm = document.querySelector('.login-form');
      const registerForm = document.querySelector('.register-form');
      const loginTitle = document.querySelector('.login-title');
      const registerTitle = document.querySelector('.register-title');
      const changeFormText = document.querySelector('.change-form');

      loginForm.classList.toggle('hidden');
      registerForm.classList.toggle('hidden');
      loginTitle.classList.toggle('hidden');
      registerTitle.classList.toggle('hidden');

      if (loginForm.classList.contains('hidden')) {
        changeFormText.textContent = 'Fazer login';
      } else {
        changeFormText.textContent = 'Fazer cadastro';
      }
    });
  </script>

</html>

templates/termoapp/navbar.html
{% load static %}

<html>
    <link rel="stylesheet" href="{% static 'termoapp/css/navbar.css' %}">
    
    <header class="navbar">
    <a href="{% url 'termoapp:termo' %}" style="text-decoration: none; color: inherit;" class="tooltip-container">
        <h1 class="title">Termo</h1>
        <span class="tooltip title-tooltip">Palavra diária</span>
    </a>
        <div class="icons-container">
            <a href="{% url 'termoapp:ranking' %}" class="tooltip-container">
                <img src="../../static/termoapp/assets/icon-ranking.svg" alt="ranking icon">
                <span class="tooltip">Ranking</span>
            </a>
            <a href="{% url 'termoapp:extra' %}" class="tooltip-container">
                <img src="../../static/termoapp/assets/icon-buy.svg" alt="shop icon" style="width: 40px;">
                <span class="tooltip">Comprar palavra</span>
            </a>
            <form id="logout-form" action="{% url 'termoapp:logout' %}?next=/" method="POST" style="display: contents;">
                {% csrf_token %}
                <a href="#" class="tooltip-container" onclick="document.getElementById('logout-form').submit(); return false;">
                    <img src="../../static/termoapp/assets/icon-logout.svg" alt="logout icon">
                    <span class="tooltip" style="left: 32%;">Logout</span>
                </a>
            </form>
        </div>
    </header>
    
</html>

templates/termoapp/ranking.html
{% load static %}

<html>
<link rel="stylesheet" href="{% static 'termoapp/css/ranking.css' %}">
{% include './navbar.html' %}

    <section class="ranking-section">
        <div class="ranking-container">
            <div class="ranking">
                <p class="table-title">Posição</p>
                <p class="table-title">Nome de usuário</p>
                <p class="table-title">Pontuação</p>
                {% for ranking in rankings %}
                    <p class="table-info">{{ ranking.ranking }}</p>
                    <p class="table-info">{{ ranking.user.username }}</p>
                    <p class="table-info">{{ ranking.score }}</p>
                {% endfor %}
            </div>
        </div>
    </section>
</html>

templates/termoapp/shop.html
{% load static %}

<html>
    <link rel="stylesheet" href="{% static 'termoapp/css/shop.css' %}">

    <div class="modal">
        <div class="modal-content">
            <div class="container">
                <p>Troque seus acertos por novas palavras!</p>
                <div class="show-coins">
                    <p>Moedas acumuladas: {{ coins }}</p>
                    <img src="../../static/termoapp/assets/icon-buy-green.svg" alt="">
                </div>
                <form action="{% url 'termoapp:buy' %}" method="POST" style="display: contents;">
                    {% csrf_token %}
                    <button type="submit" id="buy" class="buy">Comprar</button>
                </form>
            </div>
            <div class="rules">
                <p>ATENÇÃO!</p>
                <p>Você só poderá comprar uma nova palavra caso:</p>
                <ol>
                    <li>Tenha terminado a anterior</li>
                    <li>Tenha ao menos seis moedas</li>
                </ol>
            </div>
        </div>
    </div>

    {% include './base.html' %}

    {% if has_extra_words %}
        <button class="new-word">Comprar nova palavra</button>
    {% elif finished %}
        <p class="no-words">Não há mais palavras disponíveis!</p>
    {% endif %}

    <script>
        const modalContent = document.querySelector('.modal-content');
        const displayStyle = window.getComputedStyle(modalContent).getPropertyValue('display');

        if (displayStyle === 'flex') {
            const buttonBuy = document.getElementById('buy');
            const can_buy = "{{ can_buy | safe }}"
            const has_extra_words = "{{ can_buy | safe }}"

            if (can_buy === 'False') {
                buttonBuy.setAttribute('disabled', 'true');
            }

            buttonBuy.addEventListener('click', () => {
                modalContent.classList.add('closing');
            });
        }

        const has_game = "{{ has_game | safe }}";
        const modal = document.querySelector('.modal');
        if (has_game === "True") {
            modal.style.display = 'none';
        }

        const finished = "{{ finished | safe }}";
        const button = document.querySelector('.new-word');
        if (finished === "True") {
            button.style.display = 'block'
        }

        button.addEventListener('click', () => {
            modal.style.display = 'flex';
        });

    </script>
</html> 